choco install git -fy
choco install git-lfs -fy
choco install sysinternals -fy
choco install gimp -fy
choco install curl -fy
choco install nodejs -fy
choco install wget -fy
choco install inkscape -fy
choco install vscode -fy
choco install sql-server-management-studio -fy
choco install opera -fy
choco install azure-cli -fy
choco install microsoft-teams -fy
choco install audacity -fy
choco install kubernetes-cli -fy
choco install greenshot -fy
choco install postman -fy
choco install terraform -fy
choco install sqlite -fy
choco install kubernetes-helm -fy
choco install docker-desktop -fy
choco install imagemagick -fy
choco install resharper-platform -fy
choco install yed -fy
choco install ie11 -fy
choco install nswagstudio -fy
choco install sqlitebrowser -fy
choco install servicebusexplorer -fy
choco install visualstudio2019enterprise -fy
choco install drawio -fy
choco install resharper-clt -fy
choco install git-fork -fy
choco install microsoftazurestorageexplorer -fy
choco install linqpad -fy
choco install frhed -fy
choco install snoop -fy
choco install keepass -fy
choco install opencover -fy
