choco install googlechrome -fy
choco install firefox -fy
choco install vlc -fy
choco install 7zip -fy
choco install notepadplusplus -fy
choco install skype -fy
choco install paint.net -fy
choco install microsoft-edge -fy
choco install irfanview -fy
choco install microsoft-windows-terminal -fy
choco install powertoys -fy
choco install windirstat -fy
choco install mobaxterm -fy
choco install kindle -fy
choco install jdownloader -fy
choco install setpoint -fy
choco install win32diskimager -fy
